### ISSUE TITLE
PF2 Unable to Trigger Animations

### ISSUE THREAD

**Issue by BobROE** [bitkiller0/SIFToolkit#13]
I'm trying to add an animation to Fireball.

Added fireball to character
Edit fireball object to Use Texture, and select a webm file. (left loop animation on so I'll see it)
Send spell to chat
Create template from Measurement Controls menu

Nothing happens.

When I hover over the template icon it has ??? for which spell it is, and an unknown duration.

There's an error in the log (see image).
![image](https://user-images.githubusercontent.com/88206029/127688326-75b9abec-c4dc-4982-9f49-6fd571f71421.png)

**Comment by bitkiller0** [comment]
Fixed in 0.1.25

**Comment by BobROE** [comment]
I've updated to 1.127 and I still can't get it to work. I feel like I'm doing something wrong, so what is the expected flow here?

**Comment by bitkiller0** [comment]
It sounds like you're doing everything correctly. My only question is how
are you sending the spell to chat?  The error is indicating that the
correct chat message was never sent. Do you have any other modules enabled
that would affect the display of the chat message?

**Comment by BobROE** [comment]
The only modules I have enabled are this one and its dependencies.

I'm sending the spell to the chat by clicking on the spell's icon on the spellbook tab of the character sheet.

I'm no longer getting any errors in the console, but still nothing happens.

When I hover over the template icon after creating it the displayed info is ??? and Remaining: Unknown Seconds.

**Comment by bitkiller0** [comment]
I made another change that could fix this. Please update to 0.1.28 and let me know if that corrects the issue. Thanks.

**Comment by BobROE** [comment]
No change.

**Comment by Golurkcanfly** [comment]
I'm also having this issue. In addition, sometimes the "Use Texture" checkbox also disables itself after I close the spell editor, but it doesn't always disable itself. 

However, Spell Template Manager works perfectly fine.

**Comment by bitkiller0** [comment]
Circling back to this one.  Which system(s) does this seem to be affecting?

**Comment by Golurkcanfly** [comment]
My issue was also with PF2e, specifically using The Forge. For whatever reason, it worked fine with just Foundry proper. 

However, there's also another, entirely unrelated issue with SIF and PF2e following the latest system updates (occurred the day after my initial comment) due to reformatting how the spells work, which prevents the user from selecting a texture to attach to a spell. As far as I know, this restructuring of how spells work is still in progress, and this UI issue also occurs with Spell Template Manager.

**Comment by Golurkcanfly** [comment]
So far it seems to work as intended on PF2e version 2.16.4. I'll report back if I notice anything else.
